services:
  db:
    image: ankane/pgvector:latest
    container_name: attendance_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: attendance_backend
    volumes:
      - ./backend:/app
      - api_uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=attendance_db
      - SECRET_KEY=PROD_SECRET_KEY_REPLACE_ME
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: attendance_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  api_uploads:
